### ISSUE TITLE
DOL comments

### ISSUE THREAD

**Issue by tillmo** [CarloDib/ace#4]
DOL comments (starting with %%) should be highlighted in a special colour. Currently, this does not happen.

**Comment by CarloDib** [comment]
Dear @tillmo as far as i tested it works perfectly in the dol_highlight_rules file but in dollall_highlight_rules there is a lot of issues and complications that we need to talk about

**Comment by tillmo** [comment]
I just have selected "dol". How do I select dol_highlight_rules ?

**Comment by CarloDib** [comment]
dol in the modelist (the list where you can choose the language you want to highlight) refers to dol_highlight_rules and i just checked the files again and it works for me... maybe because it is highlighted in light green that's why it looks like it is not highlighted? not sure if it is the problem like what happen with me before where is the color is so similar to black where can't be seen. anyway i can show it to you tomorrow on the meeting.

**Comment by tillmo** [comment]
When using dolall, I partially works, but not for all comments:
![dolall](https://cloud.githubusercontent.com/assets/642775/14978334/60f674c0-111b-11e6-9c03-549b303d554e.png)

**Comment by CarloDib** [comment]
Ya this is the thing... when the Dol comments exist in another OMS dialect then the Dol highlighting will stop working and the highlighting for that specific OMS will only work, and that's why i said that i need to do something which will check line by line or even keyword by keyword.

**Comment by tillmo** [comment]
the comment in line 16 is still in the DOL part. Only in line 17, logic OWL is selected.

**Comment by CarloDib** [comment]
I guess line 16 and 17 are one line and actully there is no line break that's and since it found the keyword for the next logic then it will not highlight it, anyway i have few ideas in my mind how to do that but still i need to fully understand the html and javascript code.... like for example in html they made a tagmap and the tag function will check all those items in that map and will work upon that, so i guess if i do something like that tagmap and edit my code upon that then it might work, but before i am trying to fully understand the code.
